# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(default=0.0)),
                ('depositTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(default='000', max_length=40, unique=True)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(default=0.0)),
                ('depositTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoansProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('paymentPlan', models.FloatField(default=0.0)),
                ('paymentTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loansprofile',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoansProfiles', to='sacco.Users'),
        ),
        migrations.AddField(
            model_name='loansprofile',
            name='loanName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoansProfiles', to='sacco.Loans'),
        ),
        migrations.AddField(
            model_name='loandeposit',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoanDeposits', to='sacco.Users'),
        ),
        migrations.AddField(
            model_name='loandeposit',
            name='loanName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoanDeposits', to='sacco.Loans'),
        ),
        migrations.AddField(
            model_name='loandeposit',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoanDeposits', to='sacco.paymentMethod'),
        ),
        migrations.AddField(
            model_name='accountsprofile',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsProfiles', to='sacco.Users'),
        ),
        migrations.AddField(
            model_name='accountsprofile',
            name='accountName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsProfiles', to='sacco.Loans'),
        ),
        migrations.AddField(
            model_name='accountdeposit',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountDeposits', to='sacco.Users'),
        ),
        migrations.AddField(
            model_name='accountdeposit',
            name='accountName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountDeposits', to='sacco.Accounts'),
        ),
        migrations.AddField(
            model_name='accountdeposit',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountDeposits', to='sacco.paymentMethod'),
        ),
    ]
