# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_auto_20180219_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdeposit',
            old_name='UserID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='accountsprofile',
            old_name='UserID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='loandeposit',
            old_name='UserID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='loansprofile',
            old_name='UserID',
            new_name='username',
        ),
    ]
