# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 20:14
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0010_auto_20180307_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+25424204242', max_length=128),
        ),
    ]
