# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0012_auto_20180307_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsprofile',
            name='phone_number',
        ),
    ]
