# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0015_auto_20180308_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsprofile',
            name='phone_number',
        ),
    ]
