# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0017_accountsprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_pesaConfirmationPINs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=8, unique=True)),
                ('amountAsociated', models.IntegerField(default=0)),
            ],
        ),
    ]
