# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0023_auto_20180309_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansprofile',
            name='paymentTime',
            field=models.IntegerField(default=0),
        ),
    ]
