# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0024_auto_20180309_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansprofile',
            name='remainingAmount',
            field=models.FloatField(default=0),
        ),
    ]
