# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0025_loansprofile_remainingamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsprofile',
            name='accountNumber',
            field=models.IntegerField(default=0, max_length=40, unique=True),
        ),
    ]
