# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0027_auto_20180310_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsprofile',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
