# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0029_loansprofile_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeposit',
            name='accountNumber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='AccountDeposits', to='sacco.AccountsProfile'),
            preserve_default=False,
        ),
    ]
